"""add vehicle gps tracking fields

Revision ID: ab768d1fbb2c
Revises: d96c2c99e126
Create Date: 2026-09-15 22:09:08.800131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab768d1fbb2c'
down_revision: Union[str, Sequence[str], None] = 'd96c2c99e126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'longitude')
    op.drop_column('shipments', 'latitude')
    op.add_column('vehicles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('gps_speed', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('gps_heading', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('gps_accuracy', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('gps_altitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('last_gps_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'last_gps_update')
    op.drop_column('vehicles', 'gps_altitude')
    op.drop_column('vehicles', 'gps_accuracy')
    op.drop_column('vehicles', 'gps_heading')
    op.drop_column('vehicles', 'gps_speed')
    op.drop_column('vehicles', 'longitude')
    op.drop_column('vehicles', 'latitude')
    op.add_column('shipments', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
