"""create vehicles table

Revision ID: d6608c9c0908
Revises: 45b4b52fcf5f
Create Date: 2026-08-26 18:59:27.032760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6608c9c0908'
down_revision: Union[str, Sequence[str], None] = '45b4b52fcf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=30), nullable=False),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
