"""create fuel records table

Revision ID: d96c2c99e126
Revises: 197468b80fee
Create Date: 2026-08-26 20:38:36.866538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96c2c99e126'
down_revision: Union[str, Sequence[str], None] = '197468b80fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_records',
    sa.Column('fuel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('fuel_date', sa.DateTime(), nullable=False),
    sa.Column('fuel_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('fuel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_records')
    # ### end Alembic commands ###
